### ISSUE TITLE
Unable to type via VNC, keys not matching

### ISSUE THREAD

**Issue by T-X** [pzorin/qgo#45]
I am currently having trouble using qgo on this machine running Debian Sid. I connect to it via VNC, so I am not using any native keyboard but the virtual one provided by the tightvnc-server. In there I am using the attached custom keyboard layout via xmodmap.

Unfortunately typing in qgo then results in very awkward keyboard outputs: A 'u' becomes an 'm', 'i' -> 'l', 'e' -> 'g', for instance.

[xmodmap-pk-pm.txt](https://github.com/pzorin/qgo/files/183578/xmodmap-pk-pm.txt)

-----

This report is the same as: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=818232

As I am able to reproduce the issue with the sources from the master branch here on github, I thought I'd report the issue here, too.

**Comment by T-X** [comment]
Okay, happens with other Qt5 applications, like musescore, dolphin or ktimer, too. Qt4 applications are unaffected (for instance mumble).

**Comment by pzorin** [comment]
Closing because this is probably either a bug in qt or due to misconfiguration.
