### ISSUE TITLE
HOST_NOT_FOUND is defined in qt5

### ISSUE THREAD

**Issue by Fierralin** [pzorin/qgo#48]
When I used QT5 to build qgo, I found that this variable in enum ConnectionState was already defined:
    #define HOST_NOT_FOUND WSAHOST_NOT_FOUND
so I changed it into HOST_NOT_FOUND_1 and then succeeded. You'd better fix this problem.

**Comment by pzorin** [comment]
Fixed in b829eeea23e60c69a38e6f0ed07cbff6cc5c04bb
