### ISSUE TITLE
Can't detect when GNU Go resigns, goes into a busy loop

### ISSUE THREAD

**Issue by infinity0** [pzorin/qgo#49]
Easiest way to reproduce is to start a 9x9 game with a 9 handicap. Keep playing until the computer appears to hang, on the terminal it says:

~~~~
flush -> 1021 genmove white
** QGtp::slot_readFromStdout():  =1021 resign
~~~~

**Comment by pzorin** [comment]
The cursor was not being updated properly. Fixed in b068fed19249bd68913b725dabd232d3d3848cd3
