### ISSUE TITLE
Computer hangs when human player passes

### ISSUE THREAD

**Issue by gizmonicus** [pzorin/qgo#51]
This is easy to reproduce, simply open the game against a computer, place a stone and pass as your second move. qgo hangs and will never play another stone.

GNU Go 3.8
qgo 2.1.0-3

**Comment by pzorin** [comment]
Fixed in 971e2a46adaa9b8385fb69b4f8716c77f3871a1a. I am once again amazed that this pile of spaghetti code does anything useful at all.

**Comment by gizmonicus** [comment]
I'm just amazed you fixed it so quickly. Well done and thank you!
