### ISSUE TITLE
improving the build instructions in the README

### ISSUE THREAD

**Issue by thrasymache** [pzorin/qgo#53]
You had fixed an issue in the most recent development version that was bothering me, so I tried to build the development version, but I could not build qgo following the instructions as given. (Just a warning - this is my first time working with qmake.)

**Finding the project file**
after 'cd qgo; qmake' I just received usage information on qmake. I'm guessing that it doesn't search subdirectories for a project file. I had to either 'cd qgo/src; qmake' or 'cd qgo; qmake src/src.pro' or 'cd qgo; qmake src' in order for qmake to find the project file. Is there some other, better way to get qmake to find the project file, or should the README be changed to one of the above forms?

**Qt 5**
I'm currently running Ubuntu 16.04, which includes Qt 4 and defaults to Qt 4 even after you've installed Qt 5. Attempting to build with Qt 4 produces a warning from qmake, and then an error during make. Running 'qmake -qt=5' causes my machine to use Qt 5, and I get the impression that if Qt 5 wasn't installed, then it would give that error rather than trying to use Qt 4. The README already clearly states that this project uses Qt 5, but as someone who hasn't used qmake before it isn't obvious that just running qmake might run the wrong qmake. On the other hand, I've only gotten this to work on my machine and don't know if this would work on any other machine.

**Dependencies**
In addition to qt5-qmake had to install qtmultimedia5-dev in order to get it to build, but this was pretty obvious from the errors that I got. However, I got errors when building head because the qOVERLOAD function is new in Qt 5.7, and Ubuntu 16.04 only includes Qt 5.5.1.  I checked out commit d8e685f, from before the signals changes and that builds successfully with Qt 5.5.1. It might be worth noting in the README that the current version will only build with Qt 5.7 or later.

**Comment by pzorin** [comment]
Thanks for your message.
1. I remember deleting a qmake project file in the project root directory while cleaning up my IDE settings, the README is now updated accordingly.
2. I haven't had qt4 tools installed for many years and was unaware of the version issue.
3. Good that the older version works for you. I have stated the qt 5.7 dependency in the README.
